# Generated by Django 4.2.23 on 2025-09-16 22:59

import apps.api.uploads.models
import apps.core.validators.filename_extension
from django.db import migrations, models
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LazyLoadFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.api.uploads.models.get_lazy_file_path)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('loading', 'Loading'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='loading', max_length=20)),
                ('file_name', models.CharField(max_length=255, validators=[apps.core.validators.filename_extension.FilenameExtensionValidator(['mp4', 'mp3'])])),
                ('file_extension', models.CharField(editable=False, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(editable=False, null=True)),
                ('upload_id', models.CharField(editable=False, max_length=255)),
            ],
            options={
                'ordering': ['-finished_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='lazyloadfile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_file'),
        ),
        migrations.AddConstraint(
            model_name='lazyloadfile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('file_name'), name='unique_file_name'),
        ),
    ]
