# Generated by Django 4.2.23 on 2025-09-16 22:58
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
    ]
